# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K3E_RxRk0O3ADbq0sYq_PSWueZyK91kV
"""

import streamlit as st
import pandas as pd
import plotly.express as px

# 1. Page Configuration
st.set_page_config(page_title="NBA Draft Oracle", layout="wide")

# 2. Load Data (Cached so it doesn't reload on every click)
@st.cache_data
def load_data():
    # Ensure this CSV is in the same folder as this script
    df = pd.read_csv('nba_draft_predictions.csv')
    return df

df = load_data()

# 3. Sidebar Filters
st.sidebar.header("🔍 Filter Options")
selected_year = st.sidebar.selectbox("Select Draft Class", sorted(df['year'].unique(), reverse=True))

# Filter logic
year_df = df[df['year'] == selected_year].sort_values('star_prob', ascending=False).reset_index(drop=True)

# 4. Main Dashboard
st.title(f"🏀 {selected_year} NBA Draft Model Predictions")
st.markdown("""
This model calculates the probability of a college player becoming an NBA Star.
It uses **XGBoost** trained on historical data (2010-2023) and classifies players into Archetypes.
""")

# 5. Top Metrics (Key Stats)
col1, col2, col3 = st.columns(3)
if not year_df.empty:
    top_prospect = year_df.iloc[0]
    col1.metric("Highest Rated Prospect", top_prospect['player_name'], f"{top_prospect['star_prob']:.1%}")
    col2.metric("Archetype", top_prospect['archetype_note'])
    col3.metric("Projected Impact (BPM)", round(top_prospect['bpm_max'], 1))

# 6. Interactive Scatter Plot
st.subheader("Tier List: Usage vs. Star Probability")
fig = px.scatter(
    year_df,
    x="usg_max",
    y="star_prob",
    color="archetype_note",
    hover_name="player_name",
    size="bpm_max", # Dots get bigger if they had better stats
    hover_data=["height_in", "ast_per"],
    title=f"{selected_year} Class Structure",
    color_discrete_map={
        "Alien": "#ff2b2b", # Red
        "Heliocentric Engine": "#ffa600", # Orange
        "Efficiency God": "#0068c9", # Blue
        "Jumbo Creator": "#83c9ff",
        "Scoring Guard": "#ff4b4b",
        "": "grey"
    }
)
# Add "Tier Lines"
fig.add_hline(y=0.60, line_dash="dash", line_color="gold", annotation_text="MVP Tier")
fig.add_hline(y=0.45, line_dash="dash", line_color="silver", annotation_text="All-Star Tier")
st.plotly_chart(fig, use_container_width=True)

# 7. Searchable Data Table
st.subheader("📋 Full Scouting Report")
search_term = st.text_input("Search for a player:", "")

if search_term:
    display_df = year_df[year_df['player_name'].str.contains(search_term, case=False)]
else:
    display_df = year_df

# Format the dataframe for display (Add % signs, etc)
st.dataframe(
    display_df.style.background_gradient(subset=['star_prob'], cmap="Greens"),
    use_container_width=True,
    height=500
)